cloud:
  aws:
    credentials:
      access-key: # Replace with your AWS ACCESS Key
      secret-key: # Replace with your AWS SECRET Key
    region:
      static: us-east-1
    stack:
      auto: false

s3:
  endpoint: https://s3.console.aws.amazon.com # Replace with your S3 endpoint if necessary
  bucket: slydo-qr-code-bucket # Replace with your bucket name

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090
